#!/bin/bash

ROOT=$PWD

pnpm install

cd $ROOT/packages/vitest-svelte-kit
pnpm build

boostrap() {
    # remove any existing template files
    git clean -Xf . *

    # every test should have a setup script
    ./setup.sh
}

if [ -z "$1" ]
then
    for dir in $ROOT/tests/*/
    do
        cd $dir
        boostrap
    done
else
    cd $ROOT/tests/$1 && boostrap
fi

pnpm install